### ISSUE TITLE
cv2.cudacodec.createVideoReader raise "The called functionality is disabled for current build or platform in function 'throw_no_cuda'"

### ISSUE THREAD

**Issue by pfribourg-ias** [minostauros/cuda-ffmpeg-opencv-docker#1]
Hi 
thanks for this compiling work into docker.
I have the following issue while trying to use cv2.cudacodec after building 
docker-images/cuda-11.6.1/ffmpeg-5.0/opencv-4.6.0/python-3.9/Dockerfile
```
import cv2
cv2.cudacodec.createVideoReader("input.mp4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.6.0) /opencv/modules/core/include/opencv2/core/private.cuda.hpp:112: error: (-213:The function/feature is not implemented) The called functionality is disabled for current build or platform in function 'throw_no_cuda'
```
do you know what should be added to the docker to enable cudacodec.createVideoReader ?

Thanks a lot.

**Comment by minostauros** [comment]
Does `nvcc -V` work in the container?

**Comment by minostauros** [comment]
Maybe it is deprecated https://github.com/opencv/opencv/issues/11220#issuecomment-480618436
